require("_options")
require("_plugins")
require("_lsp")
require("_treesitter")
require("_telescope")
require("_whichkey")
require("_statusline")
require("_null-ls")

vim.cmd("colorscheme walh-gruvbox")
