require("_options")
require("_plugins")
require("_lsp")
require("_snippets")
require("_treesitter")
require("_telescope")
require("_whichkey")
require("_statusline")

vim.cmd("colorscheme walh-gruvbox")
